/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferByte;
import java.awt.image.DataBufferInt;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Arrays;

import javax.swing.JComponent;



import com.sun.corba.se.spi.orbutil.fsm.Input;


public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        canvas1 = new PadDraw();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        Input = new javax.swing.JTextField();
        FeedButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        TestButton = new javax.swing.JButton();
        AnswerLabel = new javax.swing.JLabel();
        ClearTest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        canvas1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Enter Correct Value:");

        Input.setText("jTextField1");
        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputActionPerformed(evt);
            }
        });



        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        TestButton.setText("Test");
        TestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestButtonActionPerformed(evt);
            }
        });

        AnswerLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        AnswerLabel.setText("A");

        ClearTest.setText("Clear");
        ClearTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(AnswerLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TestButton, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(ClearTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(AnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClearTest)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Test", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

                                         

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        canvas1.clear();
    }       
    
    private void ClearTestActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    	canvas1.clear();
    }

    private void InputActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void TestButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	Image temp = canvas1.image.getScaledInstance(50, 50, Image.SCALE_AREA_AVERAGING);
    	BufferedImage img = PadDraw.toBufferedImage(temp);
    	double db[][] = new double[temp.getHeight(null)][temp.getHeight(null)];
	    for(int i=0;i<img.getHeight(null);i++){
	    	for(int j=0;j<img.getWidth(null);j++){
	    		Color tempp = new Color(img.getRGB(j, i));
	    		int col = tempp.getBlue();
	    		if(col>0){
	    			col = 0;
	    		}else{
	    			col = 1;
	    		}
	    		db[i][j] = col;
	    	}
	    }
	    
	    //System.out.println(db.length);
	    double reduced[][] = GetRegionofInterest(db);
	    //System.out.println(reduced.length);
	    double[] toquery = Scale(reduced, 15, 24);
	    //ImgMat imgg = new ImgMat(db);
	    //imgg.GetRegionofInterest();
	    //imgg.ScaleDown(15, 24);
	    //double toquery[] = imgg.TolinearArray();
    	
    	int clas = classify.Query(toquery);
    	//System.out.println(clas);
    	if(clas <=9){
    		clas = 48 + clas;
    	}else if(clas>9 && clas <= 35){
    		clas = 65 + clas - 10;
    	}else{
    		clas = 97 + clas - 36;
    	}
    	String ans = "" + (char)(clas);
    	AnswerLabel.setText(ans);
    }                                          
    
    public double[] Scale(double imgg[][], int w,int h){
		double sW = imgg[0].length/(double)w;
		double sH = imgg.length/(double)h;
		double px,py;
		double retarr[][] = new double[h][w];
		for(int i=0;i<h;i++){
			for(int j=0;j<w;j++){
				px = Math.floor(j*sW);
				py = Math.floor(i*sH);
				retarr[i][j] = imgg[(int)py][(int)px]; 
			}
		}
		double temp[];
		temp = new double[w*h];
		for(int i=0;i<h;i++){
			for(int j=0;j<w;j++){
				temp[i*w + j] = retarr[i][j];
			}
		}
		return temp;
	}
    
	public double[][] GetRegionofInterest(double arrr[][]){
		double arr[][] = arrr;
		int n,m;
		n = arrr.length;
		m = arrr[0].length;
		int left=-1,right=-1,top=-1,bottom=-1;
		for(int i=0;i<n;i++){
			for(int j=0;j<m;j++){
				if(arr[i][j]>0 && top == -1){
					top = i;
				}
				if(arr[n-i-1][j]>0 && bottom == -1){
					bottom = n-i-1;
				}
			}
		}
		for(int i=0;i<m;i++){
			for(int j=0;j<n;j++){
				if(arr[j][i]>0 && left == -1){
					left = i;
				}
				if(arr[j][m-i-1]>0 && right == -1){
					right = m-i-1;
				}
			}
		}
		
		if(top == -1){
			top = 0;
		}
		if(left == -1){
			left = 0;
		}
		if(bottom == -1){
			bottom = n-1;
		}
		if(right == -1){
			right = m-1;
		}
		
		
		double temp[][] = new double[bottom-top+1][right - left +1];
		for(int i = top ; i <=bottom ; i++){
			for(int j = left ; j <= right; j++){
				temp[i-top][j-left] = arr[i][j];
			}
		}
		return temp;
	}
    /**
     * @param args the command line arguments
     * @throws IOException 
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        File input;
        try {
        	input = new File(filename);
        	if(input.createNewFile()){
        		System.out.println("Created fresh network!!");
        		classify = new BayesClassifier(40,26);
        	}else{
        		FileInputStream fileIn = new FileInputStream(input);
        		ObjectInputStream in = new ObjectInputStream(fileIn);
        		classify = (BayesClassifier)in.readObject();
        		in.close();
        	}
			
			
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJFrame temp = new NewJFrame();
                temp.setVisible(true);
                temp.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                    	FileOutputStream fos = null;
                        ObjectOutputStream out = null;
                        try {
                          fos = new FileOutputStream(filename);
                          out = new ObjectOutputStream(fos);
                          out.writeObject(classify);

                          out.close();
                        } catch (Exception ex) {
                          ex.printStackTrace();
                        }
                        
                    }
                });
            }
        });
        
    }

    // Variables declaration - do not modify    
    static String filename = "Bayes.ser";
    private javax.swing.JLabel AnswerLabel;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ClearTest;
    private javax.swing.JButton FeedButton;
    private javax.swing.JTextField Input;
    private javax.swing.JButton TestButton;
    private PadDraw canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    static BayesClassifier classify;
    // End of variables declaration                   
}

class PadDraw extends JComponent{
	Image image;
	//this is gonna be your image that you draw on
	Graphics2D graphics2D;
	//this is what we'll be using to draw on
	int currentX, currentY, oldX, oldY;
	//these are gonna hold our mouse coordinates
	public static BufferedImage toBufferedImage(Image img)
	{
	    if (img instanceof BufferedImage)
	    {
	        return (BufferedImage) img;
	    }

	    // Create a buffered image with transparency
	    BufferedImage bimage = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_BYTE_BINARY);

	    // Draw the image on to the buffered image
	    Graphics2D bGr = bimage.createGraphics();
	    bGr.drawImage(img, 0, 0, null);
	    bGr.dispose();

	    // Return the buffered image
	    return bimage;
	}
	//Now for the constructors
	public PadDraw(){
		setDoubleBuffered(false);
		addMouseListener(new MouseAdapter(){
			public void mousePressed(MouseEvent e){
				oldX = e.getX();
				oldY = e.getY();
			}
		});
		//if the mouse is pressed it sets the oldX & oldY
		//coordinates as the mouses x & y coordinates
		addMouseMotionListener(new MouseMotionAdapter(){
			public void mouseDragged(MouseEvent e){
				currentX = e.getX();
				currentY = e.getY();
				if(graphics2D != null){
					graphics2D.setStroke(new BasicStroke(10));
					graphics2D.drawLine(oldX, oldY, currentX, currentY);
				}
				
				repaint();
				oldX = currentX;
				oldY = currentY;
			}

		});
		//while the mouse is dragged it sets currentX & currentY as the mouses x and y
		//then it draws a line at the coordinates
		//it repaints it and sets oldX and oldY as currentX and currentY
	}

	public void paintComponent(Graphics g){
		if(image == null){
			image = createImage(getSize().width, getSize().height);
			graphics2D = (Graphics2D)image.getGraphics();
			graphics2D.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
			clear();

		}
		g.drawImage(image, 0, 0, null);
	}
	//this is the painting bit
	//if it has nothing on it then
	//it creates an image the size of the window
	//sets the value of Graphics as the image
	//sets the rendering
	//runs the clear() method
	//then it draws the image


	public void clear(){
		graphics2D.setPaint(Color.white);
		graphics2D.fillRect(0, 0, getSize().width, getSize().height);
		graphics2D.setPaint(Color.black);
		repaint();
	}
	//this is the clear
	//it sets the colors as white
	//then it fills the window with white
	//thin it sets the color back to black
	public void red(){
		graphics2D.setPaint(Color.red);
		repaint();
	}
	//this is the red paint
	public void black(){
		graphics2D.setPaint(Color.black);
		repaint();
	}
	//black paint
	public void magenta(){
		graphics2D.setPaint(Color.magenta);
		repaint();
	}
	//magenta paint
	public void blue(){
		graphics2D.setPaint(Color.blue);
		repaint();
	}
	//blue paint
	public void green(){
		graphics2D.setPaint(Color.green);
		repaint();
	}
	//green paint

}